.pragma library

const timezoneOptions = [
    // System & Universal
    { label: "Local (System Default)", value: "" },
    { label: "UTC / GMT (Coordinated Universal Time)", value: "UTC" },

    // Africa
    { label: "🇪🇬 Africa/Cairo (Egypt - EET / EEST)", value: "Africa/Cairo" },
    { label: "🇿🇦 Africa/Johannesburg (South Africa - SAST)", value: "Africa/Johannesburg" },
    { label: "🇳🇬 Africa/Lagos (West Africa - WAT)", value: "Africa/Lagos" },
    { label: "🇰🇪 Africa/Nairobi (East Africa - EAT)", value: "Africa/Nairobi" },
    { label: "🇲🇦 Africa/Casablanca (Morocco - WET / WEST)", value: "Africa/Casablanca" },
    { label: "🇩🇿 Africa/Algiers (Central Africa - CET)", value: "Africa/Algiers" },

    // Americas - North
    { label: "🇺🇸 America/New_York (US Eastern - EST / EDT)", value: "America/New_York" },
    { label: "🇺🇸 America/Chicago (US Central - CST / CDT)", value: "America/Chicago" },
    { label: "🇺🇸 America/Denver (US Mountain - MST / MDT)", value: "America/Denver" },
    { label: "🇺🇸 America/Phoenix (US Arizona - MST no DST)", value: "America/Phoenix" },
    { label: "🇺🇸 America/Los_Angeles (US Pacific - PST / PDT)", value: "America/Los_Angeles" },
    { label: "🇺🇸 America/Anchorage (Alaska - AKST / AKDT)", value: "America/Anchorage" },
    { label: "🇺🇸 Pacific/Honolulu (Hawaii - HST)", value: "Pacific/Honolulu" },
    { label: "🇨🇦 America/Toronto (Canada Eastern)", value: "America/Toronto" },
    { label: "🇨🇦 America/Vancouver (Canada Pacific)", value: "America/Vancouver" },

    // Americas - Central & South
    { label: "🇲🇽 America/Mexico_City (Mexico - CST)", value: "America/Mexico_City" },
    { label: "🇧🇷 America/Sao_Paulo (Brazil - BRT)", value: "America/Sao_Paulo" },
    { label: "🇦🇷 America/Argentina/Buenos_Aires (Argentina - ART)", value: "America/Argentina/Buenos_Aires" },
    { label: "🇨🇱 America/Santiago (Chile - CLT / CLST)", value: "America/Santiago" },
    { label: "🇨🇴 America/Bogota (Colombia - COT)", value: "America/Bogota" },
    { label: "🇵🇪 America/Lima (Peru - PET)", value: "America/Lima" },
    { label: "🇻🇪 America/Caracas (Venezuela - VET)", value: "America/Caracas" },

    // Asia & Middle East
    { label: "🇯🇵 Asia/Tokyo (Japan - JST)", value: "Asia/Tokyo" },
    { label: "🇰🇷 Asia/Seoul (South Korea - KST)", value: "Asia/Seoul" },
    { label: "🇨🇳 Asia/Shanghai (China - CST)", value: "Asia/Shanghai" },
    { label: "🇭🇰 Asia/Hong_Kong (Hong Kong - HKT)", value: "Asia/Hong_Kong" },
    { label: "🇸🇬 Asia/Singapore (Singapore - SGT)", value: "Asia/Singapore" },
    { label: "🇹🇼 Asia/Taipei (Taiwan - CST)", value: "Asia/Taipei" },
    { label: "🇮🇩 Asia/Jakarta (Indonesia Western - WIB)", value: "Asia/Jakarta" },
    { label: "🇹🇭 Asia/Bangkok (Thailand, Vietnam - ICT)", value: "Asia/Bangkok" },
    { label: "🇮🇳 Asia/Kolkata (India - IST)", value: "Asia/Kolkata" },
    { label: "🇵🇰 Asia/Karachi (Pakistan - PKT)", value: "Asia/Karachi" },
    { label: "🇧🇩 Asia/Dhaka (Bangladesh - BST)", value: "Asia/Dhaka" },
    { label: "🇦🇪 Asia/Dubai (UAE, Gulf - GST)", value: "Asia/Dubai" },
    { label: "🇸🇦 Asia/Riyadh (Saudi Arabia - AST)", value: "Asia/Riyadh" },
    { label: "🇮🇱 Asia/Jerusalem (Israel - IST / IDT)", value: "Asia/Jerusalem" },
    { label: "🇮🇷 Asia/Tehran (Iran - IRST / IRDT)", value: "Asia/Tehran" },
    { label: "🇶🇦 Asia/Qatar (Qatar - AST)", value: "Asia/Qatar" },

    // Australia & Pacific
    { label: "🇦🇺 Australia/Sydney (NSW, VIC, ACT, TAS - AEST / AEDT)", value: "Australia/Sydney" },
    { label: "🇦🇺 Australia/Melbourne (Victoria - AEST / AEDT)", value: "Australia/Melbourne" },
    { label: "🇦🇺 Australia/Adelaide (South Australia - ACST / ACDT)", value: "Australia/Adelaide" },
    { label: "🇦🇺 Australia/Darwin (Northern Territory - ACST)", value: "Australia/Darwin" },
    { label: "🇦🇺 Australia/Brisbane (Queensland - AEST)", value: "Australia/Brisbane" },
    { label: "🇦🇺 Australia/Perth (Western Australia - AWST)", value: "Australia/Perth" },
    { label: "🇦🇺 Australia/Hobart (Tasmania - AEST / AEDT)", value: "Australia/Hobart" },
    { label: "🇦🇺 Australia/Lord_Howe (Lord Howe Island)", value: "Australia/Lord_Howe" },
    { label: "🇳🇿 Pacific/Auckland (New Zealand - NZST / NZDT)", value: "Pacific/Auckland" },
    { label: "🇫🇯 Pacific/Fiji (Fiji - FJT / FJST)", value: "Pacific/Fiji" },

    // Europe & Russia
    { label: "🇬🇧 Europe/London (UK - GMT / BST)", value: "Europe/London" },
    { label: "🇮🇪 Europe/Dublin (Ireland - GMT / IST)", value: "Europe/Dublin" },
    { label: "🇫🇷 Europe/Paris (France - CET / CEST)", value: "Europe/Paris" },
    { label: "🇩🇪 Europe/Berlin (Germany - CET / CEST)", value: "Europe/Berlin" },
    { label: "🇪🇸 Europe/Madrid (Spain - CET / CEST)", value: "Europe/Madrid" },
    { label: "🇮🇹 Europe/Rome (Italy - CET / CEST)", value: "Europe/Rome" },
    { label: "🇳🇱 Europe/Amsterdam (Netherlands - CET / CEST)", value: "Europe/Amsterdam" },
    { label: "🇧🇪 Europe/Brussels (Belgium - CET / CEST)", value: "Europe/Brussels" },
    { label: "🇨🇭 Europe/Zurich (Switzerland - CET / CEST)", value: "Europe/Zurich" },
    { label: "🇦🇹 Europe/Vienna (Austria - CET / CEST)", value: "Europe/Vienna" },
    { label: "🇸🇪 Europe/Stockholm (Sweden - CET / CEST)", value: "Europe/Stockholm" },
    { label: "🇳🇴 Europe/Oslo (Norway - CET / CEST)", value: "Europe/Oslo" },
    { label: "🇩🇰 Europe/Copenhagen (Denmark - CET / CEST)", value: "Europe/Copenhagen" },
    { label: "🇵🇱 Europe/Warsaw (Poland - CET / CEST)", value: "Europe/Warsaw" },
    { label: "🇨🇿 Europe/Prague (Czechia - CET / CEST)", value: "Europe/Prague" },
    { label: "🇭🇺 Europe/Budapest (Hungary - CET / CEST)", value: "Europe/Budapest" },
    { label: "🇬🇷 Europe/Athens (Greece - EET / EEST)", value: "Europe/Athens" },
    { label: "🇫🇮 Europe/Helsinki (Finland - EET / EEST)", value: "Europe/Helsinki" },
    { label: "🇷🇴 Europe/Bucharest (Romania - EET / EEST)", value: "Europe/Bucharest" },
    { label: "🇺🇦 Europe/Kyiv (Ukraine - EET / EEST)", value: "Europe/Kyiv" },
    { label: "🇹🇷 Europe/Istanbul (Turkey - TRT)", value: "Europe/Istanbul" },
    { label: "🇷🇺 Europe/Moscow (Russia - MSK)", value: "Europe/Moscow" },

    // Fixed UTC Offsets (UTC-12 to UTC+14)
    { label: "UTC+14:00 (Line Islands, Kiribati)", value: "UTC+14" },
    { label: "UTC+13:00 (Tonga, Samoa)", value: "UTC+13" },
    { label: "UTC+12:45 (Chatham Islands)", value: "UTC+12:45" },
    { label: "UTC+12:00 (Marshall Islands, Tuvalu)", value: "UTC+12" },
    { label: "UTC+11:00 (Solomon Islands, Vanuatu)", value: "UTC+11" },
    { label: "UTC+10:30 (Lord Howe Standard)", value: "UTC+10:30" },
    { label: "UTC+10:00 (Guam, Papua New Guinea)", value: "UTC+10" },
    { label: "UTC+09:30 (Australian Central Standard)", value: "UTC+9:30" },
    { label: "UTC+09:00 (East Timor, Palau)", value: "UTC+9" },
    { label: "UTC+08:45 (Australian Central Western)", value: "UTC+8:45" },
    { label: "UTC+08:00 (Perth, Singapore, Beijing)", value: "UTC+8" },
    { label: "UTC+07:00 (Bangkok, Jakarta, Hanoi)", value: "UTC+7" },
    { label: "UTC+06:30 (Myanmar, Cocos Islands)", value: "UTC+6:30" },
    { label: "UTC+06:00 (Dhaka, Almaty)", value: "UTC+6" },
    { label: "UTC+05:45 (Nepal Standard)", value: "UTC+5:45" },
    { label: "UTC+05:30 (India Standard, Sri Lanka)", value: "UTC+5:30" },
    { label: "UTC+05:00 (Pakistan, Tashkent, Maldives)", value: "UTC+5" },
    { label: "UTC+04:30 (Afghanistan)", value: "UTC+4:30" },
    { label: "UTC+04:00 (Dubai, Baku, Yerevan, Tbilisi)", value: "UTC+4" },
    { label: "UTC+03:30 (Iran Standard)", value: "UTC+3:30" },
    { label: "UTC+03:00 (Moscow, Riyadh, Nairobi, Baghdad)", value: "UTC+3" },
    { label: "UTC+02:00 (Athens, Cairo, Helsinki, Johannesburg)", value: "UTC+2" },
    { label: "UTC+01:00 (Paris, Berlin, Rome, Madrid, Lagos)", value: "UTC+1" },
    { label: "UTC+00:00 (UTC, GMT, London, Reykjavik, Accra)", value: "UTC+0" },
    { label: "UTC-01:00 (Cabo Verde, Azores)", value: "UTC-1" },
    { label: "UTC-02:00 (South Georgia, Fernando de Noronha)", value: "UTC-2" },
    { label: "UTC-03:00 (Buenos Aires, Sao Paulo, Montevideo)", value: "UTC-3" },
    { label: "UTC-03:30 (Newfoundland Standard)", value: "UTC-3:30" },
    { label: "UTC-04:00 (Santiago, Caracas, Halifax, Manaus)", value: "UTC-4" },
    { label: "UTC-05:00 (New York, Toronto, Bogota, Lima)", value: "UTC-5" },
    { label: "UTC-06:00 (Chicago, Mexico City, Guatemala)", value: "UTC-6" },
    { label: "UTC-07:00 (Denver, Phoenix, Edmonton)", value: "UTC-7" },
    { label: "UTC-08:00 (Los Angeles, Vancouver, Tijuana)", value: "UTC-8" },
    { label: "UTC-09:00 (Anchorage, Gambier Islands)", value: "UTC-9" },
    { label: "UTC-09:30 (Marquesas Islands)", value: "UTC-9:30" },
    { label: "UTC-10:00 (Honolulu, Tahiti, Rarotonga)", value: "UTC-10" },
    { label: "UTC-11:00 (American Samoa, Niue, Midway)", value: "UTC-11" },

    // Custom Write-In Option
    { label: "✏️ Custom Timezone / City / Offset...", value: "__CUSTOM__" }
];

const localeOptions = [
    { label: "System Default", value: "" },
    { label: "🇬🇧 English (US / UK - en_US / en_GB)", value: "en_US" },
    { label: "🇫🇷 French (France - fr_FR)", value: "fr_FR" },
    { label: "🇩🇪 German (Germany - de_DE)", value: "de_DE" },
    { label: "🇪🇸 Spanish (Spain - es_ES)", value: "es_ES" },
    { label: "🇲🇽 Spanish (Mexico - es_MX)", value: "es_MX" },
    { label: "🇮🇹 Italian (Italy - it_IT)", value: "it_IT" },
    { label: "🇵🇹 Portuguese (Portugal - pt_PT)", value: "pt_PT" },
    { label: "🇧🇷 Portuguese (Brazil - pt_BR)", value: "pt_BR" },
    { label: "🇯🇵 Japanese (Japan - ja_JP)", value: "ja_JP" },
    { label: "🇰🇷 Korean (South Korea - ko_KR)", value: "ko_KR" },
    { label: "🇨🇳 Chinese (Simplified - zh_CN)", value: "zh_CN" },
    { label: "🇹🇼 Chinese (Traditional - zh_TW)", value: "zh_TW" },
    { label: "🇷🇺 Russian (Russia - ru_RU)", value: "ru_RU" },
    { label: "🇺🇦 Ukrainian (Ukraine - uk_UA)", value: "uk_UA" },
    { label: "🇵🇱 Polish (Poland - pl_PL)", value: "pl_PL" },
    { label: "🇳🇱 Dutch (Netherlands - nl_NL)", value: "nl_NL" },
    { label: "🇸🇪 Swedish (Sweden - sv_SE)", value: "sv_SE" },
    { label: "🇳🇴 Norwegian (Norway - nb_NO)", value: "nb_NO" },
    { label: "🇩🇰 Danish (Denmark - da_DK)", value: "da_DK" },
    { label: "🇫🇮 Finnish (Finland - fi_FI)", value: "fi_FI" },
    { label: "🇨🇿 Czech (Czechia - cs_CZ)", value: "cs_CZ" },
    { label: "🇸lovakia (sk_SK)", value: "sk_SK" },
    { label: "🇭🇺 Hungarian (Hungary - hu_HU)", value: "hu_HU" },
    { label: "🇷🇴 Romanian (Romania - ro_RO)", value: "ro_RO" },
    { label: "🇧🇬 Bulgarian (Bulgaria - bg_BG)", value: "bg_BG" },
    { label: "🇬🇷 Greek (Greece - el_GR)", value: "el_GR" },
    { label: "🇹🇷 Turkish (Turkey - tr_TR)", value: "tr_TR" },
    { label: "🇸🇦 Arabic (Saudi Arabia - ar_SA)", value: "ar_SA" },
    { label: "🇮🇳 Hindi (India - hi_IN)", value: "hi_IN" },
    { label: "🇮🇩 Indonesian (Indonesia - id_ID)", value: "id_ID" },
    { label: "🇻🇳 Vietnamese (Vietnam - vi_VN)", value: "vi_VN" },
    { label: "🇹🇭 Thai (Thailand - th_TH)", value: "th_TH" },
    { label: "✏️ Custom Locale...", value: "__CUSTOM__" }
];
